version: '3.9'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"   
    environment:
      - SERVICES=sqs,sns,s3
      - DEBUG=0
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 10s

  app:
    build: .
    container_name: my_poll_app
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - QUESTION_QUEUE_URL=http://localstack:4566/000000000000/question-queue
      - CHOICE_QUEUE_URL=http://localstack:4566/000000000000/choice-queue
      - USER_QUEUE_URL=http://localstack:4566/000000000000/user-queue
      - STATS_QUEUE_URL=http://localstack:4566/000000000000/stats-queue
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_NAME=polls_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DD_TRACE_ENABLED=false
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6380
      - REDIS_DB=0

    volumes:
      - .:/app
    ports:
      - "8000:8000" 
    command: >
      sh -c "python wait_for_db.py &&
             python -m polls.messaging.messaging_setup &&
             python -m polls.messaging.consumers.consumer_manager &&
             python manage.py runserver 0.0.0.0:8000"


volumes:
  localstack_data:
