# docker-compose.publisher.yml
version: "3.9"
services:
  # ---------- Check & Wait for LocalStack ----------
  wait_localstack:
    image: curlimages/curl:latest
    container_name: wait_localstack_publisher
    entrypoint: >
      sh -c "
        echo '⏳ Waiting for LocalStack...';
        until curl -s http://localstack:4566/_localstack/health | grep -Po '\"overall\":\\s*\"running\"'; do
          sleep 2;
        done;
        echo '✅ LocalStack is ready!';
      "
    networks:
      - vpn

  # ---------- LocalStack ----------
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_service
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns,s3,lambda,kinesis
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - vpn

  # ---------- Setup Publisher ----------
  setup_localstack_publisher:
    build: .
    container_name: setup_localstack_publisher_service
    environment:
      LOCALSTACK_ENDPOINT: http://localstack:4566
      AWS_DEFAULT_REGION: us-east-1
      APP_ROLE: PUBLISHER
      DD_TRACE_ENABLED: false
    command: python manage.py setup_localstack
    networks:
      - vpn
    depends_on:
      - localstack
      - wait_localstack

  mysql_dev:
    image: mysql:8.0
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
      MYSQL_DATABASE: ms1_db
    ports:
      - "3307:3306"  # port على الجهاز المضيف
    volumes:
      - ./mysql_dev_data:/var/lib/mysql
    networks:
      - vpn
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql_local:
    image: mysql:8.0
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_db
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_pass
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_local_data:/var/lib/mysql
    networks:
      - vpn
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
  db_setup:
    build: .
    container_name: db_setup_service
    environment:
      # لو عندك أي ENV متعلقة بالداتا
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - vpn
    depends_on:
      mysql_dev:
        condition: service_healthy
      mysql_local:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
      - ./db:/app/db
    command: python /app/scripts/run_all.py


  # ---------- Publisher App ----------
  publisher:
    build: .
    container_name: my_poll_app_publisher
    environment:
      DJANGO_ENV: local
      APP_ROLE: PUBLISHER
      LOCALSTACK_ENDPOINT: http://localstack:4566
      AWS_DEFAULT_REGION: us-east-1
      DD_TRACE_ENABLED: false
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - vpn
    depends_on:
      - setup_localstack_publisher
    command: >
      sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"

networks:
  vpn:
    name: vpn
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
