# Generated by Django 5.2.6 on 2025-10-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_created_by_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
